### ISSUE TITLE
Issue while installing scottyjs

### ISSUE THREAD

**Issue by secabhi** [stojanovic/scottyjs#1]
abhishek@edgeitadmin-Latitude-E5450:~$ scotty {options}

events.js:163
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: tmp/.scotty-db/LOCK: No such file or directory
    at /usr/local/lib/node_modules/scottyjs/node_modules/levelup/lib/levelup.js:117:34
    at /usr/local/lib/node_modules/scottyjs/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
abhishek@edgeitadmin-Latitude-E5450:~$ scotty

events.js:163
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: tmp/.scotty-db/LOCK: No such file or directory
    at /usr/local/lib/node_modules/scottyjs/node_modules/levelup/lib/levelup.js:117:34
    at /usr/local/lib/node_modules/scottyjs/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
abhishek@edgeitadmin-Latitude-E5450:~$ npm -v
4.2.0
abhishek@edgeitadmin-Latitude-E5450:~$ node -v
v7.8.0
abhishek@edgeitadmin-Latitude-E5450:~$

**Comment by stojanovic** [comment]
Hm, I thought I fixed that one. It's related to leveldb and read only systems.

Can you tell me 2 things:
- Which system are you using?
- Is it working with `sudo`, ie. `sudo scotty --spa`?

Thanks

**Comment by secabhi** [comment]
I am using Linux - `Ubuntu 14.04.5 LTS , VERSION="14.04.5 LTS, Trusty Tahr .`
Ya, it's working when I use `sudo scotty ` .
Thx for help

**Comment by secabhi** [comment]
Hi Next step I am getting this message. Am i doing something wrong here
abhishek@edgeitadmin-Latitude-E5450:~/Downloads$ sudo scotty --spa --source ./hello.txt

 💥  Beam up failed 💥 
 You have attempted to create more buckets than allowed
abhishek@edgeitadmin-Latitude-E5450:~/Downloads$

**Comment by stojanovic** [comment]
This is AWS S3 error, only 100 buckets are allowed per account and it seems that you already have 100 buckets.
More info: http://docs.aws.amazon.com/AmazonS3/latest/dev/DevPayBucketLimitation.html

**Comment by secabhi** [comment]
ok if I can put in an existing bucket then I am getting the same warning message
 ```
💥  Beam up failed 💥 
 You have attempted to create more buckets than allowed
abhishek@edgeitadmin-Latitude-E5450:~$ sudo scotty --source ./hello.txt --bucket pub

 💥  Beam up failed 💥 
 You have attempted to create more buckets than allowed
abhishek@edgeitadmin-Latitude-E5450:~$ 
```

**Comment by stojanovic** [comment]
Because it's trying to create bucket first and fallbacks to update if it is failing with "already exists" error. In your case, it is throwing this error instead "already exists" one.

I'll fix that during the day today, thanks for helping. I am removing leveldb to fix that `sudo` issue right now.

**Comment by stojanovic** [comment]
Can you install v1.3 and try:

1. Without `sudo`
2. With `sudo` and `--update` flag for the existing bucket

Thanks

**Comment by stojanovic** [comment]
Just tried on another machine that has `sudo` issue and it works. Reopen if you still have the problem.
