### ISSUE TITLE
CNAME support

### ISSUE THREAD

**Issue by amirilovic** [stojanovic/scottyjs#11]
Hi,

Thanks for a great tool! I wrote very similar one and I would like to send PR for some things that I don't see like CNAME support. Are you planning to add this? Is it ok if I work on it?

**Comment by stojanovic** [comment]
That would be great, that's on the list of planned features.
How would you implement that?
I would like to have SSL support for custom domains, but need to check how to do that.

For the command, original idea was `scotty --domain example.com` and `scotty -d example.com`, but feel free to recommend anything you thing would work better.

Also, share your lib if it's open source :)

**Comment by amirilovic** [comment]
Tool I worked on is at https://github.com/foundcenter/spajs. The idea is the same, to do quick setup and deployment of static websites/spa to aws.
Tool has two commands:
- `init` setup bucket, cf distribution, ssl... with CNAME support. Also has support for different environments, all configs are saved under .spajs/ in current dir - so you can easily target: staging, testing, production - whatever env.
- `deploy` take files from certain dir and sync with s3 bucket. This is implemented using couple of gulp tasks (I had to come up with something fast :) ) I've added also resource minification and versioning and deploy (maybe out of scope for this tool) using sync (awspublish module) - not just copy. The interesting part is caching since that is going to be crucial for performance.

Take a look tell me what you think :)

Now back to the issue, the flow would go like this:
- If `--domain` is specified we would first check if there is a valid certificate on ACM, if there isn't that we would prompt the user if he want's to request one. The info what to do next would be displayed to the user like: `Verification email has been sent to admin@domain.com. Please verify certificate request and re-run scotty.` To get already verified SSL certificate from ACM take a look at: https://github.com/foundcenter/spajs/blob/f6ed94127cd75307c9c367ef4e0f99fde3f29120/src/initializer.ts#L187 The catch is that in order for certificate to be valid for CF distribution it needs to be requested in `us-east-1`.
- Once certificate is setup scotty would needs to create bucket with name corresponding to domain and setup CNAME and custom certificate on CF. To set CF certificate take a look at: https://github.com/foundcenter/spajs/blob/f6ed94127cd75307c9c367ef4e0f99fde3f29120/src/initializer.ts#L174

Would this work?

**Comment by ckaatz-here** [comment]
I started for the dns pointing part with the following: https://github.com/ckaatz-here/scottyjs/commit/9a3c89eb977e8d8d52e51267f2cd3ba968844337 but it is in progress

**Comment by stojanovic** [comment]
Spajs looks nice :)
I'll try it a bit later today.

I think resource compression is out of scope for tool like this, it should be handled by some other tool before deployment, ie. webpack or gulp.

Flow looks good. In v2 we can optimize everything a bit more, but this sounds great for v1.
I need to write the plan for v2 somewhere, but we'll wait a bit more just to see if people are using Scotty before we do some of the improvements.

I'll close this issue and wait for PR :)

Thanks!

**Comment by stojanovic** [comment]
@ckaatz-here just saw your comment, looks like a good start. I have some small comments, but I'll wait for PR because they are not affecting the concept.
@amirilovic do you want to help @ckaatz-here, or? Not sure what's the best way to proceed, I didn't expect so many PRs for `scotty` haha :)

**Comment by amirilovic** [comment]
@ckaatz-here I see that you are focusing on r53, did you plan to add ssl support, do you need any help regarding this?

**Comment by ckaatz-here** [comment]
@amirilovic I did not intend to add ssl support but would love to get help with that part.

**Comment by amirilovic** [comment]
@ckaatz-here Great, I'll work on that.
