### ISSUE TITLE
deploy doesn't work in docker context

### ISSUE THREAD

**Issue by ckaatz-here** [stojanovic/scottyjs#2]
💥  Beam up failed 💥
 xsel: Can't open display: (null)
: Inappropriate ioctl for device

Docker base image is: node:8.4
scotty -w -r us-east-1 -f

Also the -r option on an initial run doesn't work, it will every time deploy to eu-central-1

**Comment by stojanovic** [comment]
Hm, `-f` is causing `-r` to fail, that's easy to fix.

Other issue seems like a copy to clipboard issue, I'll try to fix it today.

Thanks for reporting.

**Comment by stojanovic** [comment]
Btw, why do you need `-f` anyway?

**Comment by ckaatz-here** [comment]
I tried that after I figured out that the -r option didn't seem to work.

**Comment by ckaatz-here** [comment]
actually that copy feature is nice, but if you already write out the link, it should be just fine without copying as it adds complexity.

**Comment by stojanovic** [comment]
Yes, we'll add try/catch there and ignore the error.
It needs some improvements, but this is MVP :)

**Comment by ckaatz-here** [comment]
I really appreciate that MVP 👍

**Comment by stojanovic** [comment]
On NPM - v1.4.0
