### ISSUE TITLE
Improper url provided for eu-west-2 region

### ISSUE THREAD

**Issue by chdsbd** [stojanovic/scottyjs#21]
Creating a website in the eu-west-2 region provides the following url from scotty, `http://<bucket-name>.s3-website-eu-west-2.amazonaws.com`, but this doesn't work. Looking on the S3 console, the url should be `http://<bucket-name>.s3-website.eu-west-2.amazonaws.com`.

It seems like the simple fix would be to print the url with a `.` in place of the `-`, since it appears all regions support the first syntax, while only some support the latter.

**Comment by stojanovic** [comment]
Thanks for reporting it, do you want to send a PR?

**Comment by stojanovic** [comment]
Fix will be on NPM in a few minutes.
