### ISSUE TITLE
PR #19 broke standard AWS credential provider chaining

### ISSUE THREAD

**Issue by dijitalmunky** [stojanovic/scottyjs#22]
PR #19 inadvertently has broken the normal AWS provider chaining described at https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

Steps to reproduce:
---
1. Ensure that you have no `~/.aws/credentials` file
2. Set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to known good values
3. Run a scotty command to communicate with s3.  I used: `scotty -s <dir> -b <bucket-name> -u -r <region>`

Expected results:
---
Output similar to the following (works with v 1.9 and below):
```
   bucket ✤ <bucket-name>
   upload ✤ completed (195.81Kb, 0.81s)

Successfully beamed up! http://<bucket-name>.s3.amazonaws.com/
This link should be copied to your clipboard now.

CDN URL: null
CloudFront is super slow, this link should be valid in next 10 minutes or so.
```
Actual Results:
---
```
Set AWS credentials first. Guide is available here: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
```
Unfortunately, this ends up breaking our CI system, where there are no config files contain credentials, only secret environment variables that are only set when the CI job runs.

Recommended action(s):
---
AWS' provider chain allows one to actually specify the profile to use in the `~/.aws/credentials` file by setting the environment variable `AWS_PROFILE`.  For example, to use the profile named dev, add the following to the `~/.aws/credentials` file:
```
[dev]
AWS_ACCESS_KEY_ID=<access-key>
AWS_SECRET_ACCESS_KEY=<secret-key>
```

Then set the environment variable and run scotty:
```
export AWS_PROFILE=dev
scotty -s <dir> -b <bucket-name> -u -r <region>
```
If this behavior was the original intent of PR #19, then the PR can simply be reverted (this is actually how I had been running scotty on my local machine for a while now).

Alternatively, if the above was not the intent of the original PR, then a code guard can be added to the `setAWSProfile` function of `bin/scotty.js` to only execute the code in that function if and only if the `--profile` argument is passed to the application (I can submit a PR for this if needed).

**Comment by stojanovic** [comment]
Fixed and going to NPM as 1.10.1
