### ISSUE TITLE
us-east-1 should be the default

### ISSUE THREAD

**Issue by ckaatz-here** [stojanovic/scottyjs#3]
? Where do you want me to beam you up to? us-east-1

 💥  Beam up failed 💥
 The specified location-constraint is not valid

[documented here](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html)

**Comment by stojanovic** [comment]
Ok, valid reason. I am from Europe, but it will be updated :)

**Comment by ckaatz-here** [comment]
I am also from europe :-)
