### ISSUE TITLE
Feature: define credentials with env variables

### ISSUE THREAD

**Issue by wkentdag** [stojanovic/scottyjs#31]
I see on the version 2.0 roadmap that there are updates planned for the AWS credential management process overall, but I wanted to call attention to an immediate issue I'm having with the current version: Scotty.js doesn't work with CircleCI 2.0.

There's [currently](https://discuss.circleci.com/t/aws-credentials-in-machine-executor/10058/6) [a](https://discuss.circleci.com/t/aws-credentials-not-auto-imported-anymore/19431) [bug](https://discuss.circleci.com/t/circleci-2-0-cant-find-aws/11492/6) on Circle's end where AWS credentials are not getting added to `~/.aws/credentials`. Most people are using the `aws` CLI and can therefore work around it by passing their credentials as build environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

After digging into the scotty [source code](https://github.com/stojanovic/scottyjs/blob/857b48267e3e548836217bc1da3ed9a44b8a57ed/bin/scotty.js#L160) a bit, it looks like the [`AWS.SharedIniFileCredentials`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html) class that's getting used under the hood *only* looks for credentials at `~/.aws/credentials` and doesn't check for credentials in any of the other config settings defined [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) under "Configuration Settings and Precedence".

I realize this is a bug on Circle's end and not on this repo, but I just wanted to call it out since it's forcing me to drop Scotty.js. I have never used the AWS JS SDK but will try to find an alternative to `SharedIniFileCredentials` that will support my use case later this week.

**Comment by stojanovic** [comment]
@wkentdag I think I did a quick fix on master branch, can you try it? If it works I'll publish it on NPM tomorrow. If not I'll test it tomorrow.

**Comment by Jack12816** [comment]
@stojanovic It's working as expected. No credentials issue anymore on master.

**Comment by wkentdag** [comment]
@stojanovic sorry for extreme delay - it works! Think you can close this out.

**Comment by stojanovic** [comment]
Sorry for delay on my side. Closing it. It's on NPM as 1.10.2.
